// Pulls the published content from the admin backend and writes src/data/cms-snapshot.js, so the
// build (and the prerendered HTML that Google and social bots read) contains whatever was
// published in the admin. Runs in CI right before `npm run build`:
//
//   CMS_API_URL=https://oryantechsol.com/api node scripts/fetch-cms.mjs
//
// It never fails the build: if the backend isn't installed yet, is down, or returns something
// unexpected, the committed default snapshot (= the static content in src/data) is kept.

import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const target = path.join(root, 'src/data/cms-snapshot.js')
const postsTarget = path.join(root, 'src/data/cms-posts.js')
const base = (process.env.CMS_API_URL || '').replace(/\/$/, '')

async function getJson(url) {
  const response = await fetch(url, { headers: { Accept: 'application/json' }, signal: AbortSignal.timeout(20000) })
  const type = response.headers.get('content-type') ?? ''
  if (!response.ok || !type.includes('json')) throw new Error(`${url} -> ${response.status} ${type}`)
  return response.json()
}

async function main() {
  if (!base) {
    console.log('CMS: CMS_API_URL not set — keeping the committed snapshot.')
    return
  }
  const content = await getJson(`${base}/public/content`)
  if (typeof content?.version !== 'string' || !content.managed) throw new Error('unexpected /public/content shape')

  let posts = []
  if (content.managed.posts) {
    const data = await getJson(`${base}/public/posts`)
    if (!Array.isArray(data?.posts)) throw new Error('unexpected /public/posts shape')
    posts = data.posts
  }

  const snapshot = {
    version: content.version,
    managed: content.managed,
    settings: content.settings ?? {},
    nav: content.nav ?? [],
    texts: content.texts ?? [],
    team: content.team ?? null,
    projects: content.projects ?? [],
  }
  const header =
    '// GENERATED by scripts/fetch-cms.mjs from the admin backend — do not edit by hand.\n' +
    '// The committed copy is the empty default ("nothing managed yet"); CI overwrites it before building.\n'
  await fs.writeFile(target, `${header}export default ${JSON.stringify(snapshot, null, 1)}\n`)
  // Articles go in their own module so their text stays out of the main bundle (see src/data/posts-light.js).
  await fs.writeFile(postsTarget, `${header}export default ${JSON.stringify(posts, null, 1)}\n`)
  console.log(
    `CMS: snapshot v${snapshot.version} — ${posts.length} posts, ${snapshot.projects.length} projects, ` +
      `${snapshot.texts.length} text overrides, ${snapshot.nav.length} menu items, team ${snapshot.team ? 'managed' : 'static'}.`,
  )
}

main().catch((error) => {
  console.log(`CMS: could not fetch content (${error.message}) — keeping the committed snapshot.`)
})
